# Generated by Django 4.2.1 on 2023-06-06 12:34

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_rename_location_point_geom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="point",
            name="geom",
            field=django.contrib.gis.db.models.fields.PointField(
                srid=4326, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="point",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
